id: dbbad24dd5244915ad979169156daaa8
initial_creation_type: ebook
source_metadata:
  title: test
  subtitle: ''
  authors:
  - test
  collection: ''
  publisher: ''
  id: test
  cover: tmp5nazijj8.jpg
  credit: tmpzpli8ixa.jpg
