id: dbbad24dd5244915ad979169156daaa8
initial_creation_type: ebook
created_at: 8/04/2021
last_modified_at: 25/11/2021
source_metadata:
  title: test
  subtitle: ''
  authors:
  - test
  collection: ''
  publisher: ''
  id: test
  cover: tmp5nazijj8.jpg
  credit: tmpzpli8ixa.jpg
